name: ci

on:
  push:
    branches:
    - '*'
    - '*/*'
    - '**'

jobs:
  ubuntu:
    name: Compile & Test
    strategy:
      matrix:
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Build
      run: make debug

    - uses: Swatinem/rust-cache@v1

  macos:
    name: Compile & Test
    strategy:
      matrix:
        os: [macos-10.15]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-apple-darwin
        default: true
        override: true

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Build
      run: make debug

    - uses: Swatinem/rust-cache@v1
